import cx_Oracle

# Dados de conexão
username = 'PDBADMIN'
password = 'Not@1943ma'
dsn = 'localhost:1521/nome_servico'

# Conectando ao Oracle
connection = cx_Oracle.connect(username, password, dsn)
cursor = connection.cursor()
# Criando mais tabelas de exemplo
cursor.execute("""
    CREATE TABLE departamento (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        nome VARCHAR2(100),
        PRIMARY KEY (id)
    )
""")

cursor.execute("""
    CREATE TABLE funcionario (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        nome VARCHAR2(100),
        departamento_id NUMBER,
        PRIMARY KEY (id),
        FOREIGN KEY (departamento_id) REFERENCES departamento(id)
    )
""")
# Exemplo: criando uma tabela
cursor.execute("""
    CREATE TABLE exemplo (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        nome VARCHAR2(100),
        PRIMARY KEY (id)
    )
""")

print("Tabela criada com sucesso!")

cursor.close()
connection.close()